### ISSUE TITLE
Support for go 1.20

### ISSUE THREAD

**Issue by ronanh** [loov/lensm#16]
It seems that lensm does not support go 1.20 binaries yet.

Also getting some errors when trying to compile my program with go 1.19:
`unable to load source from "gofile../Users/rhi/code/table/page.go": open gofile../Users/rhi/code/table/page.go: no such file or directory`

**Comment by egonelbre** [comment]
Can you try again with the latest branch. I updated the goobj file parsing code, but I'm not quite sure that's the problem.

Do you use some flags when building the binary?

**Comment by ronanh** [comment]
Updated the code, this fixed the issue with go 1.20 binary, thanks.
The other issue with the path not found is gone, it was likely because I had no main(), only tests.

**Comment by egonelbre** [comment]
Yeah, I don't think it will work with just compiled packages. It does require an actual binary. You should be able to use `go test -c .` to create the binary that you can open.
